# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff54fbe9f85d4a822c6f21bc751400d3c662a633e27a37ac277debb57bb80e2f17ec5597d4d26dbaa64200704d55093ddfae9c5da8988159ffea604aa4f41ef0

test:
  secret_key_base: 48743ba31b2cc4534c4d366699ddb6723222c9cdcd870210d8d18e0d9f34d975bc75e8543b26989042cb3a626d86ce71b08f95dc2508f25f97fe217c07fb5d2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
